"""Medio de pago muchos_muchos

Revision ID: 048a4edc41cc
Revises: 3577890166e8
Create Date: 2025-11-05 11:11:00.388721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '048a4edc41cc'
down_revision = '3577890166e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medios_pago_cuentas',
    sa.Column('medio_pago_cuenta_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('medio_pago_id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas.cuenta_id'], ),
    sa.ForeignKeyConstraint(['medio_pago_id'], ['medios_de_pago.medio_pago_id'], ),
    sa.PrimaryKeyConstraint('medio_pago_cuenta_id')
    )
    with op.batch_alter_table('medios_de_pago', schema=None) as batch_op:
        batch_op.drop_constraint('medios_de_pago_cuenta_origen_id_fkey', type_='foreignkey')
        batch_op.drop_column('cuenta_origen_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medios_de_pago', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cuenta_origen_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('medios_de_pago_cuenta_origen_id_fkey', 'cuentas', ['cuenta_origen_id'], ['cuenta_id'])

    op.drop_table('medios_pago_cuentas')
    # ### end Alembic commands ###
