"""empty message

Revision ID: 073f61e22e78
Revises: 8d769f4f3903
Create Date: 2024-01-08 21:12:57.294462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '073f61e22e78'
down_revision = '8d769f4f3903'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inversion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cerrada', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inversion', schema=None) as batch_op:
        batch_op.drop_column('cerrada')

    # ### end Alembic commands ###
