"""empty message

Revision ID: 1d35b29e002d
Revises: e8c3b0a886a2
Create Date: 2024-01-08 16:23:12.399546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d35b29e002d'
down_revision = 'e8c3b0a886a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historical_money', schema=None) as batch_op:
        batch_op.add_column(sa.Column('liquidez', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historical_money', schema=None) as batch_op:
        batch_op.drop_column('liquidez')

    # ### end Alembic commands ###
