"""Añadido divisa

Revision ID: 242cdbceda1e
Revises: 9e5a5199c918
Create Date: 2025-11-04 13:23:02.205121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '242cdbceda1e'
down_revision = '9e5a5199c918'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('divisas',
    sa.Column('divisa_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('divisa', sa.Text(), nullable=False),
    sa.Column('simbolo', sa.String(), nullable=False),
    sa.Column('abreviacion', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('divisa_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('divisas')
    # ### end Alembic commands ###
