"""Description income

Revision ID: 254f77ec2433
Revises: d36430b71088
Create Date: 2025-11-04 20:12:44.806896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '254f77ec2433'
down_revision = 'd36430b71088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saldo_cuenta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saldo_cuenta', schema=None) as batch_op:
        batch_op.drop_column('descripcion')

    # ### end Alembic commands ###
