"""empty message

Revision ID: 2569001ed744
Revises: db84f2ac6e76
Create Date: 2023-10-04 21:53:56.869657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2569001ed744'
down_revision = 'db84f2ac6e76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria_inversion',
    sa.Column('categoria_inv_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('categoria_inv', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('categoria_inv_id')
    )
    op.create_table('medios_de_pago',
    sa.Column('medio_pago_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('medio_pago', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('medio_pago_id')
    )
    op.create_table('inversion',
    sa.Column('inversion_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('monto', sa.Integer(), nullable=False),
    sa.Column('rentab_esperada', sa.Float(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('categoria', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria'], ['categoria_inversion.categoria_inv_id'], ),
    sa.PrimaryKeyConstraint('inversion_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inversion')
    op.drop_table('medios_de_pago')
    op.drop_table('categoria_inversion')
    # ### end Alembic commands ###
