"""Nuevas tablas income

Revision ID: 3235fce79c29
Revises: 4446ed7e77e4
Create Date: 2025-11-04 19:30:42.148938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3235fce79c29'
down_revision = '4446ed7e77e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cuentas',
    sa.Column('cuenta_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('institucion_financiera', sa.Text(), nullable=False),
    sa.Column('nombre_cuenta', sa.Text(), nullable=False),
    sa.Column('saldo', sa.Float(), nullable=False),
    sa.Column('divisa', sa.Integer(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['divisa'], ['divisas.divisa_id'], ),
    sa.PrimaryKeyConstraint('cuenta_id')
    )
    op.create_table('transferencias',
    sa.Column('transferencia_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cuenta_origen', sa.Integer(), nullable=False),
    sa.Column('cuenta_destino', sa.Integer(), nullable=False),
    sa.Column('monto_enviado', sa.Float(), nullable=False),
    sa.Column('divisa_origen', sa.Integer(), nullable=False),
    sa.Column('monto_recibido', sa.Float(), nullable=False),
    sa.Column('divisa_destino', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cuenta_destino'], ['cuentas.cuenta_id'], ),
    sa.ForeignKeyConstraint(['cuenta_origen'], ['cuentas.cuenta_id'], ),
    sa.ForeignKeyConstraint(['divisa_destino'], ['divisas.divisa_id'], ),
    sa.ForeignKeyConstraint(['divisa_origen'], ['divisas.divisa_id'], ),
    sa.PrimaryKeyConstraint('transferencia_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transferencias')
    op.drop_table('cuentas')
    # ### end Alembic commands ###
