"""Medio de pago cuenta descuento

Revision ID: 3577890166e8
Revises: 48824b14587f
Create Date: 2025-11-05 11:07:05.110907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3577890166e8'
down_revision = '48824b14587f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medios_de_pago', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cuenta_origen_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'cuentas', ['cuenta_origen_id'], ['cuenta_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medios_de_pago', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cuenta_origen_id')

    # ### end Alembic commands ###
