"""Divisa en gastos

Revision ID: 4446ed7e77e4
Revises: 242cdbceda1e
Create Date: 2025-11-04 14:51:26.945585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4446ed7e77e4'
down_revision = '242cdbceda1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gastos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('divisa', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'divisas', ['divisa'], ['divisa_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gastos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('divisa')

    # ### end Alembic commands ###
