"""Medio de pago_ gasto

Revision ID: 48824b14587f
Revises: 254f77ec2433
Create Date: 2025-11-04 20:23:22.831175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48824b14587f'
down_revision = '254f77ec2433'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gastos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medio_pago_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'medios_de_pago', ['medio_pago_id'], ['medio_pago_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gastos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('medio_pago_id')

    # ### end Alembic commands ###
