"""empty message

Revision ID: 5d8434f27ae3
Revises: dd29e595296c
Create Date: 2024-01-08 17:01:33.596670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d8434f27ae3'
down_revision = 'dd29e595296c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria_ingreso',
    sa.Column('categoria_ingreso_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('categoria_ingreso', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('categoria_ingreso_id')
    )
    op.create_table('ingresos',
    sa.Column('ingreso_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('monto', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('categoria', sa.Integer(), nullable=False),
    sa.Column('hash_formato', sa.Text(), nullable=True),
    sa.Column('id_df_formato', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria'], ['categoria_ingreso.categoria_ingreso_id'], ),
    sa.PrimaryKeyConstraint('ingreso_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingresos')
    op.drop_table('categoria_ingreso')
    # ### end Alembic commands ###
