"""empty message

Revision ID: 66cffad57ce4
Revises: e163bd6f723a
Create Date: 2024-01-08 15:07:45.234149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66cffad57ce4'
down_revision = 'e163bd6f723a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bienes',
    sa.Column('bien_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('valor_inicial', sa.Integer(), nullable=False),
    sa.Column('valor_venta', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('bien_id')
    )
    with op.batch_alter_table('gastos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hash_formato', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('id_df_formato', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('id_patrimonio', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'bienes', ['id_patrimonio'], ['bien_id'])

    with op.batch_alter_table('inversion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hash_formato', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('id_df_formato', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inversion', schema=None) as batch_op:
        batch_op.drop_column('id_df_formato')
        batch_op.drop_column('hash_formato')

    with op.batch_alter_table('gastos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_patrimonio')
        batch_op.drop_column('id_df_formato')
        batch_op.drop_column('hash_formato')

    op.drop_table('bienes')
    # ### end Alembic commands ###
