"""a

Revision ID: 73be6e5bb0dc
Revises: 
Create Date: 2023-06-17 12:05:27.338956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73be6e5bb0dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('user', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('user')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    # ### end Alembic commands ###
