"""empty message

Revision ID: 8d769f4f3903
Revises: 7ef678984761
Create Date: 2024-01-08 19:45:44.953501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d769f4f3903'
down_revision = '7ef678984761'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plataformas_inversion',
    sa.Column('plataforma_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plataforma', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('plataforma_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plataformas_inversion')
    # ### end Alembic commands ###
