"""users

Revision ID: 8e6552aab188
Revises: 
Create Date: 2023-06-17 18:04:23.313952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e6552aab188'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria_gasto',
    sa.Column('categoria_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('categoria', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('categoria_id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gastos',
    sa.Column('gasto_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('monto', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('categoria', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria'], ['categoria_gasto.categoria_id'], ),
    sa.PrimaryKeyConstraint('gasto_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gastos')
    op.drop_table('usuarios')
    op.drop_table('categoria_gasto')
    # ### end Alembic commands ###
