"""Add fs_uniquifier field

Revision ID: 9e5a5199c918
Revises: 073f61e22e78
Create Date: 2025-05-01 21:38:58.821824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e5a5199c918'
down_revision = '073f61e22e78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fs_uniquifier', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['fs_uniquifier'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('fs_uniquifier')

    # ### end Alembic commands ###
