"""Nuevas tablas income v2

Revision ID: a2deb7f0830c
Revises: 3235fce79c29
Create Date: 2025-11-04 19:42:57.292784

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a2deb7f0830c'
down_revision = '3235fce79c29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saldo_cuenta',
    sa.Column('saldo_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.Column('saldo', sa.Float(), nullable=False),
    sa.Column('fecha_movimiento', sa.Date(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas.cuenta_id'], ),
    sa.PrimaryKeyConstraint('saldo_id')
    )
    with op.batch_alter_table('cuentas', schema=None) as batch_op:
        batch_op.drop_column('fecha_actualizacion')
        batch_op.drop_column('saldo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cuentas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saldo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('fecha_actualizacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))

    op.drop_table('saldo_cuenta')
    # ### end Alembic commands ###
