"""Avoiding duplicates

Revision ID: d36430b71088
Revises: a2deb7f0830c
Create Date: 2025-11-04 20:10:04.013938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd36430b71088'
down_revision = 'a2deb7f0830c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saldo_cuenta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hash_formato', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('id_df_formato', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saldo_cuenta', schema=None) as batch_op:
        batch_op.drop_column('id_df_formato')
        batch_op.drop_column('hash_formato')

    # ### end Alembic commands ###
