"""empty message

Revision ID: e163bd6f723a
Revises: 2569001ed744
Create Date: 2023-10-05 22:57:34.770255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e163bd6f723a'
down_revision = '2569001ed744'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_money',
    sa.Column('histórico_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('patrimonio', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('histórico_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historical_money')
    # ### end Alembic commands ###
