"""empty message

Revision ID: e8c3b0a886a2
Revises: 66cffad57ce4
Create Date: 2024-01-08 16:20:20.638096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8c3b0a886a2'
down_revision = '66cffad57ce4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historical_money', schema=None) as batch_op:
        batch_op.add_column(sa.Column('historico_id', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.drop_column('histórico_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historical_money', schema=None) as batch_op:
        batch_op.add_column(sa.Column('histórico_id', sa.INTEGER(), server_default=sa.text('nextval(\'"historical_money_histórico_id_seq"\'::regclass)'), autoincrement=True, nullable=False))
        batch_op.drop_column('historico_id')

    # ### end Alembic commands ###
